#!/bin/sh

cwd=$(pwd)
sed -i "/^[ ]*\[SchemeUrg\]/ d" ~/.cache/wal/colors-wal-dwm.h

cd /opt/suckless/dwm
sudo rm config.h drw.o dwm dwm.o util.o
sudo make
sudo make clean install
sudo rm config.h drw.o dwm dwm.o util.o

cd /opt/suckless/dmenu
sudo rm config.h dmenu dmenu.o drw.o stest stest.o util.o
sudo make
sudo make clean install
sudo rm config.h dmenu dmenu.o drw.o stest stest.o util.o

cd /opt/suckless/st
sudo rm config.h st st.o x.o
sudo make
sudo make clean install
sudo rm config.h st st.o x.o

cd $cwd
